#define MAINPREFIX z
#define PREFIX sez

#include "script_version.hpp"

#define VERSION MAJOR.MINOR
#define VERSION_AR MAJOR,MINOR,PATCHLVL,BUILD
#define VERSION_CONFIG version = VERSION; versionStr = QUOTE(MAJOR.MINOR.PATCHLVL-BUILD); versionAr[] = {VERSION_AR}

#define REQUIRED_VERSION 2.14

#ifdef COMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(sez - COMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(sez - COMPONENT)
#endif
